---
mariadb_append_mroonga_repository: true

mariadb_packages:
  - mariadb-client
  - mariadb-backup
  - mariadb-server
  - mysqltuner
  - mariadb-mroonga
  - groonga-tokenizer-mecab

mariadb_databases:
  - name: app_dev
    password: app_dev_p455w0rd
    hosts:
      - 127.0.0.1
      - ::1
      - localhost
  - name: app_staging
    user: staging
    password: staging_p455w0rd
    hosts:
      - 127.0.0.1
      - ::1
      - localhost
  - name: app_test
  - name: app_prod

mariadb_users:
  - name: mackerel_agent
    password: mackerel_agent_p455w0rd
    hosts:
      - 127.0.0.1
      - ::1
      - localhost
    privs:
      - "*.*:PROCESS,SUPER,REPLICATION CLIENT"
  - name: app_test
    password: app_test_p455w0rd
    hosts:
      - 127.0.0.1
      - ::1
      - localhost
    privs:
      - "*.*:All"
  - name: app_prod
    password: app_prod_p455w0rd
    hosts:
      - 127.0.0.1
      - ::1
      - localhost
    privs:
      - "*.*:All"
