---
- name: Install MariaDB packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ mariadb_packages }}"
- name: Install dependency packages
  ansible.builtin.apt:
    name: "{{ mariadb_dependency_packages }}"
