---
- name: Install dependency packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Get apt-source package
  ansible.builtin.get_url:
    url: https://packages.groonga.org/debian/groonga-apt-source-latest-{{ ansible_facts.distribution_release }}.deb
    dest: /usr/local/src/groonga-apt-source-latest-{{ ansible_facts.distribution_release }}.deb
    mode: "0644"
- name: Add mroonga repository
  ansible.builtin.apt:
    deb: /usr/local/src/groonga-apt-source-latest-{{ ansible_facts.distribution_release }}.deb
