---
- name: install dependency packages
  apt:
    name: "{{ mariadb_expect_dependency_packages  }}"
- name: execute mysql_secure_installation
  expect:
    command: mysql_secure_installation
    responses:
      "Enter current password for root": ""
      "Switch to unix_socket authentication": "y"
      "Change the root password?": "y"
      "New password:": "{{ mariadb_root_password }}"
      "Re-enter new password:": "{{ mariadb_root_password }}"
      "Remove anonymous users?": "y"
      "Disallow root login remotely?": "y"
      "Remove test database and access to it?": "y"
      "Reload privilege tables now?": "y"
  no_log: true
# - name: check root user connection setting
#   stat:
#     path: /root/.my.cnf
#   register: result
# - block:
#     - name: create mysql secure installation query file
#       template:
#         src: mysql_secure_installation.sql.j2
#         dest: /tmp/mysql_secure_installation.sql
#         mode: "0600"
#       no_log: true
#     - name: execute mysql secure installation
#       shell: mysql -u root mysql </tmp/mysql_secure_installation.sql
#     - name: remove mysql secure installation query file
#       file:
#         path: /tmp/mysql_secure_installation.sql
#         state: absent
#   when: not result.stat.exists
# - name: change root password
#   command: mysqladmin password "{{ mariadb_root_password }}" -u root
#   when: result.stat.exists
# - name: create root user connection setting
#   ini_file:
#     path: /root/.my.cnf
#     section: client
#     option: "{{ item.option }}"
#     value: "{{ item.value }}"
#     mode: "0600"
#     create: true
#   loop:
#     - option: host
#       value: localhost
#     - option: user
#       value: root
#     - option: password
#       value: "{{ mariadb_root_password }}"
#   no_log: true
