---
- name: MariaDB is active and enabled on system startup
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: true
- name: Ensure allow MariaDB port
  community.general.ufw:
    rule: allow
    port: "3306"
    proto: tcp
  when: mariadb_allow_connect_other_host | default(false)
