---
- name: Ensure includedir setting
  ansible.builtin.lineinfile:
    path: "{{ mariadb_config_base_dir }}/my.cnf"
    line: "!includedir {{ mariadb_config_dir }}/"
  notify: restart mariadb
- name: Create MariaDB setting files
  ansible.builtin.template:
    src: custom.cnf.j2
    dest: "{{ mariadb_config_dir }}/99-custom.cnf"
    mode: "0644"
  notify: restart mariadb
- name: Create log directory
  ansible.builtin.file:
    path: /var/log/mysql
    state: directory
    mode: "0755"
    owner: mysql
    group: mysql
- name: MariaDB is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: mariadb
    state: started
    enabled: true
- name: Install expect dependency packages
  ansible.builtin.apt:
    name: "{{ mariadb_expect_dependency_packages }}"
- name: Get registerd root password
  ansible.builtin.command:
    cmd: cat /root/mariadb_root_password
    removes: /root/mariadb_root_password
  changed_when: false
  register: cat_result
- name: Set registerd root password variable
  ansible.builtin.set_fact:
    mariadb_registerd_root_password: "{{ cat_result.stdout }}"
- name: Find mysql_secure_installation task file
  ansible.builtin.set_fact:
    mysql_secure_installation_task_file: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}/{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - tasks/setting
- name: Execute mysql_secure_installation
  ansible.builtin.include_tasks: "{{ mysql_secure_installation_task_file }}"
  when: mysql_secure_installation_task_file | length > 0
  tags:
    - mysql_secure_installation
    - molecule-idempotence-notest
- name: Add/update root password file
  ansible.builtin.template:
    src: root_password.j2
    dest: /root/mariadb_root_password
    mode: "0600"
