---
- name: restart mariadb
  ansible.builtin.systemd_service:
    name: mariadb
    state: restarted
- name: restart firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: restarted
